version: '3'

services:
  awesome:
   image: awesome
   ports:
     - 8080
   environment:
     - SERVICE_PORTS=8080
   deploy:
     resources:
       limits:
         cpus: '0.024'
         memory: 18M
       reservations:
         cpus: '0.024'
         memory: 18M
     replicas: 4
     update_config:
       parallelism: 2
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - awesome
    environment:
      - BALANCE=leastconn
      - EXTRA_GLOBAL_SETTINGS=debug
      - RSYSLOG_DESTINATION=127.0.0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 1936:1936
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  web:
    driver: overlay
